const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const store={get:(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},set:(k,v)=>localStorage.setItem(k,JSON.stringify(v))};
const defaultCheck={sleep:8,soreness:3,motivation:8,pain:0};
const defaultWeek=[['Mo','Sprint & Core'],['Di','Krafttraining'],['Mi','Technik'],['Do','Spielanalyse'],['Fr','Gym'],['Sa','Aktivierung'],['So','Spiel']];
let trainings=store.get('luca6_trainings',[]),check=store.get('luca6_check',defaultCheck),match=store.get('luca6_match',null);
const skills={Passspiel:92,Spielintelligenz:91,Ausdauer:89,Zweikampf:84,Scanning:86,Explosivität:71,'Top Speed':69,Kopfball:63};
function readiness(c){return Math.max(15,Math.min(100,Math.round(65+c.sleep*3+c.motivation*2-c.soreness*3-c.pain*7)))}
function coach(c){const r=readiness(c);if(c.pain>=4)return{r,color:'red',status:'Hoch',headline:'Heute keine harte Belastung.',msg:'Der angegebene Schmerz ist zu hoch für Sprint- oder Krafttraining. Regeneration und fachliche Abklärung stehen im Vordergrund.',focus:'Regeneration',intensity:'Sehr niedrig',duration:'15–25 min',session:'Recovery & Mobility',plan:['10 min lockere Bewegung','Mobilität nur schmerzfrei','Keine Sprints oder Sprünge']};if(r<55)return{r,color:'red',status:'Hoch',headline:'Heute Erholung priorisieren.',msg:'Schlaf, Müdigkeit oder Motivation sprechen gegen eine intensive Einheit.',focus:'Erholung',intensity:'Niedrig',duration:'20–30 min',session:'Recovery Day',plan:['15–20 min sehr locker','Mobility Hüfte & Sprunggelenk','Früh schlafen und gut essen']};if(r<75)return{r,color:'amber',status:'Mittel',headline:'Kontrollierter Trainingstag.',msg:'Training ist möglich, aber Umfang und maximale Sprints sollten reduziert werden.',focus:'Technik & Kraft',intensity:'Mittel',duration:'35–45 min',session:'Controlled Quality',plan:['Dynamisches Warm-up 10 min','4 × 10 m technisch sauber','Core & einbeinige Stabilität','Cooldown 8 min']};return{r,color:'green',status:'Niedrig',headline:'Heute ist ein Qualitätstag.',msg:'Gute Voraussetzungen für kurze explosive Aktionen mit vollständigen Pausen. Keine unnötigen Dauerläufe danach.',focus:'Explosivität',intensity:'Hoch',duration:'45–55 min',session:'Acceleration Day',plan:['Warm-up + Lauf-ABC 12 min','4 × 10 m Antritt, volle Pause','4 × 20 m Beschleunigung','3 × 5 Sprünge, sauber landen','Core 3 Runden','Cooldown 8 min']}}
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function renderWeek(){const html=defaultWeek.map(([d,x],i)=>`<div class="week-row"><b>${d}</b><span>${x}</span><em>${i<3?'✓':'○'}</em></div>`).join('');$('#weekPlan').innerHTML=html;$('#weekPlanLarge').innerHTML=html}
function renderMatch(){if(!match){$('#matchOpponent').textContent='Noch nicht eingetragen';$('#matchMeta').textContent='Datum, Uhrzeit und Gegner im Kalender ergänzen.';$('#countdownDays').textContent='–';return}const d=new Date(match.date),days=Math.max(0,Math.ceil((d-Date.now())/86400000));$('#matchOpponent').textContent=`${esc(match.opponent)} vs. TSG Sprockhövel`;$('#matchMeta').textContent=`${d.toLocaleDateString('de-DE',{weekday:'long',day:'2-digit',month:'2-digit',year:'numeric'})} · ${d.toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'})} Uhr · ${match.venue}`;$('#countdownDays').textContent=days}
function render(){const c=coach(check),now=Date.now(),week=trainings.filter(t=>now-t.ts<604800000),mins=week.reduce((a,t)=>a+t.duration,0);$('#readinessValue').textContent=c.r;$('#loadStatus').textContent=c.status;$('#loadDetail').textContent=c.color==='green'?'Sehr gut – weiter so!':c.color==='amber'?'Umfang kontrollieren':'Erholung priorisieren';$('#gaugeNeedle').style.transform=`rotate(${180+(100-c.r)*1.35}deg)`;$('#coachHeadline').textContent=c.headline;$('#coachMessage').textContent=c.msg;$('#coachFocus').textContent=c.focus;$('#coachFocusDetail').textContent=c.focus;$('#coachIntensity').textContent=c.intensity;$('#coachDuration').textContent=c.duration;$('#missionTitle').textContent=c.session;$('#missionText').textContent=c.msg;$('#sessionPlan').innerHTML=c.plan.map(x=>`<li>${x}</li>`).join('');const b=$('#sessionBadge');b.className=`badge ${c.color}`;b.textContent=c.color==='green'?'EMPFOHLEN':c.color==='amber'?'KONTROLLIERT':'RECOVERY';$('#weekMinutes').textContent=mins+' min';$('#weekSessions').textContent=week.length+' Einheiten';$('#consistency').textContent=week.length+' Tage';const score=Math.min(95,Math.round(74+Math.min(10,week.length)*.8));$('#proScore').textContent=score;$('#scoreTrend').textContent=`+${Math.max(0,score-74)} diese Woche`;$('#trainingList').innerHTML=trainings.length?trainings.slice().reverse().slice(0,10).map(t=>`<div class="activity"><div><strong>${esc(t.type)}</strong><small>${new Date(t.ts).toLocaleDateString('de-DE')} · RPE ${t.rpe}${t.note?' · '+esc(t.note):''}</small></div><b>${t.duration} min</b></div>`).join(''):'<p class="muted">Noch keine Einheit gespeichert.</p>';$('#skills').innerHTML=Object.entries(skills).map(([k,v])=>`<div class="skill-row"><span>${k}</span><div class="bar"><i style="width:${v}%"></i></div><b>${v}</b></div>`).join('');renderMatch()}
function show(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('.nav-btn').forEach(t=>t.classList.toggle('active',t.dataset.view===id));scrollTo({top:350,behavior:'smooth'})}
$$('.nav-btn').forEach(b=>b.onclick=()=>show(b.dataset.view));$$('[data-view-jump]').forEach(b=>b.onclick=()=>show(b.dataset.viewJump));
['soreness','motivation','pain','rpe'].forEach(id=>{const e=$('#'+id),o=$('#'+id+'Out');e.oninput=()=>o.textContent=e.value});
$('#checkinForm').onsubmit=e=>{e.preventDefault();check={sleep:+$('#sleep').value,soreness:+$('#soreness').value,motivation:+$('#motivation').value,pain:+$('#pain').value};store.set('luca6_check',check);render();show('coach')};
$('#trainingForm').onsubmit=e=>{e.preventDefault();trainings.push({type:$('#trainingType').value,duration:+$('#duration').value,rpe:+$('#rpe').value,note:$('#note').value.trim(),ts:Date.now()});store.set('luca6_trainings',trainings);$('#note').value='';render();show('tracking')};
$('#matchForm').onsubmit=e=>{e.preventDefault();if(!$('#opponent').value||!$('#matchDate').value)return;match={opponent:$('#opponent').value.trim(),date:$('#matchDate').value,venue:$('#matchVenue').value};store.set('luca6_match',match);render();show('dashboard')};
Object.entries(check).forEach(([k,v])=>{if($('#'+k))$('#'+k).value=v;if($('#'+k+'Out'))$('#'+k+'Out').textContent=v});
$('#stravaConnect').onclick=()=>{const cfg=window.LUCA6_CONFIG||{};if(!cfg.STRAVA_BACKEND_URL||!cfg.STRAVA_CLIENT_ID){$('#stravaStatus').textContent='Strava-Backend noch nicht eingerichtet. Nutze die README-Anleitung.';return}const url=new URL('https://www.strava.com/oauth/authorize');url.searchParams.set('client_id',cfg.STRAVA_CLIENT_ID);url.searchParams.set('redirect_uri',cfg.STRAVA_BACKEND_URL+'/oauth/callback');url.searchParams.set('response_type','code');url.searchParams.set('approval_prompt','auto');url.searchParams.set('scope','read,activity:read_all');location.href=url};
let deferred;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferred=e;$('#installBtn').classList.remove('hidden')});$('#installBtn').onclick=async()=>{if(deferred){deferred.prompt();await deferred.userChoice;deferred=null;$('#installBtn').classList.add('hidden')}};
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');renderWeek();render();
